- name: To create new project {{ namespace }}
  shell: "{{ oc_binary }}  new-project  {{ namespace }}"
  register: create_project

- fail:
    msg: "Failed to create new project {{ namespace }}"
  when: create_project.rc != 0

- name: To create the image stream
  shell: "{{ oc_binary }} -n {{ namespace }} import-image internal-image:int --from {{ external_image_name }} --confirm"

- name: To add tag tag1 to the imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} tag internal-image:int internal-image:tag1"

- name: To add tag tag2 to the imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} tag internal-image:int internal-image:tag2 --alias=true"

- name: To create the new imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} import-image internal-image:3.9 --from {{ external_image_name }}:3.9"

- name: To add tag tag3 to the imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} tag internal-image:3.9 internal-image:tag3"

- name: To add tag latest to the imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} tag internal-image:3.9 internal-image:latest"

- name: To add tag tag4 to the imagestreams
  shell: "{{ oc_binary }} -n {{ namespace }} tag internal-image:3.9 internal-image:tag4 --alias=true"

  
