- name: To check if imagestreams is imported successfully
  shell: "{{ oc_binary }} get is -n {{ namespace }}"
  register: img_info

- debug:
    msg: "{{ img_info }}"

- fail:
    msg: "Failed to import imagestreams internal-image in namespace {{ namespace }}"
  when: not (img_info.stdout is search("internal-image"))

- name: To check if imagestreams is tagged correctly
  shell: "{{ oc_binary }} get istag -n {{ namespace }}"
  register: tag_info

- debug:
    msg: "{{ tag_info }}"

- fail:
    msg: "Failed to import imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:int"))

- fail:
    msg: "Failed to add tag1 to imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:tag1"))

- fail:
    msg: "Failed to add tag2 to imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:tag2"))

- fail:
        msg: "Failed to import imagestreams internal-image:v3.9 in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:3.9"))

- fail:
    msg: "Failed to add tag3 to imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:tag3"))

- fail:
    msg: "Failed to add latest to imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:latest"))

- fail:
    msg: "Failed to add tag4 to imagestreams internal-image in namespace {{ namespace }}"
  when: not (tag_info.stdout is search("internal-image:tag4"))


