- name: To check if imagestream is imported successfully
  shell: "{{ oc_binary }} get is -n {{ namespace }}"
  register: img_info

- debug:
    msg: "{{ img_info }}"

- fail:
    msg: "Failed to import imagestram {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (img_info.stdout is search({{ internal_image_name }}))

- name: To check if imagestream is imported successfully
  shell: "{{ oc_binary }} get istag -n {{ namespace }}"
  register: tag_int_info

- debug:
    msg: "{{ tag_int_info }}"

- fail:
    msg: "Failed to import imagestram {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_int_info.stdout is search("{{ internal_image_name }}:int"))

- fail:
    msg: "Failed to add tag1 to imagestream {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_tag1_info.stdout is search("{{ internal_image_name }}:tag1"))

- fail:
    msg: "Failed to add tag2 to imagestream {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_tag2_info.stdout is search("{{ internal_image_name }}:tag2"))

- fail:
        msg: "Failed to import imagestram {{ internal_image_name }}:v3.9 in namespace {{ namespace }}"
  when: not (tag_v39_info.stdout is search("{{ internal_image_name }}:v3.9"))

- fail:
    msg: "Failed to add tag3 to imagestream {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_tag3_info.stdout is search("{{ internal_image_name }}:tag3"))

- fail:
    msg: "Failed to add latest to imagestream {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_latest_info.stdout is search("{{ internal_image_name }}:latest"))

- fail:
    msg: "Failed to add tag4 to imagestream {{ internal_image_name }} in namespace {{ namespace }}"
  when: not (tag_tag4_info.stdout is search("{{ internal_image_name }}:tag4"))

